os: linux
dist: xenial
language: ruby

services:
  - docker

before_install:
  - docker build -t ronbraha/road-trip-backend .
script:
  - docker run ronbraha/road-trip-backend test --import-map=import_map.json --config=tsconfig.json --allow-env tests/version.test.ts
  - docker run ronbraha/road-trip-backend test --import-map=import_map.json --config=tsconfig.json --allow-env --unstable --allow-read --allow-net tests/port.test.ts

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'road-trip-api'
  env: 'Roadtripapi-env'
  bucket: 'elasticbeanstalk-eu-west-1-510833883070'
  bucket_path: 'road-trip-api'
  access_key_id: '$AWS_ACCESS_KEY_ID'
  secret_access_key: '$AWS_SECRET_ACCESS_KEY'
  on:
    branch: main
